# The full url to be hosted (e.g., http://example.com/notes)
site_url: "https://ketozhang.github.io/StaticPy"
site_brand: "StaticPy"
site_title: "StaticPy"
author: "StaticPy"
# # All paths are relative to project path
# # Absolute path: `/dir`
# # Relative path: `dir` or `dir/`
# # Where your markdown notes live
# source_path: "notes/"
# # Where you like to output the html to be served
build_path: "docs/" # Use `docs/` for GitHub Pages compatibility.

# Flask defaults
template_path: "templates/"
static_path: "static/"

root_pages:
  about: "about.html"

contexts:
  # keys should be url endpoint (e.g., for mysite.com/notes key is notes)
  notes:
    source_path: "notes"
    url: "/notes"
    template: "note.html"
  posts:
    source_path: "posts"
    url: "/posts"
    template: "post.html"

navbar:
  notes:
    text: "Notes"
    url: "/notes"
  posts:
    text: "Posts"
    url: "/posts"
  about:
    text: "About"
    url: "/about"

social_links:
  cv:
    text: "CV"
    url: "static/CV.html"
    icon: "/static/images/icons8-applicant-24.png"
  linkedin:
    text: "LinkedIn"
    url: "#"
    icon: "/static/images/icons8-linkedin.svg"
  email:
    text: "Email"
    url: "#"
    icon: "/static/images/icons8-envelope.svg"
  github:
    text: "GitHub"
    url: "#"
    icon: "/static/images/icons8-github.svg"
