# The full url to be hosted (e.g., http://example.com/notes)
site_url: 'https://ketozhang.github.io/StaticPy'
site_brand: 'StaticPy'
site_title: 'StaticPy'
author: 'StaticPy'
# # All paths are relative to project path
# # Absolute path: `/dir`
# # Relative path: `dir` or `dir/`
# # Where your markdown notes live
# source_path: 'notes/'
# # Where you like to output the html to be served
build_path: 'docs/' # Use `docs/` for GitHub Pages compatibility.

# Flask defaults
template_path: 'templates/'
static_path: 'static/'

root_pages:
  about: 'about.html'

contexts:
  # keys should be url endpoint (e.g., for mysite.com/notes key is notes)
  notes:
    source_path: 'notes'
    url: '/notes'
    template: 'note.html'
  posts:
    source_path: 'posts'
    url: '/posts'
    template: 'post.html'

navbar:
  notes:
    text: 'Notes'
    url: '/notes'
  posts:
    text: 'Posts'
    url: '/posts'
  about:
    text: 'About'
    url: '/about'

social_links:
  cv:
    text: 'CV'
    url: '/static/CV.html'
    icon: 'https://img.icons8.com/material/24/0000 00/parse-resume.png'
  linkedin:
    text: 'Email'
    url: 'mailto:test'
    icon: 'https://img.icons8.com/material/24/000000/filled-message.png'
  email:
    text: 'LinkedIn'
    url: '#'
    icon: 'https://img.icons8.com/ios-glyphs/24/000000/linkedin.png'
  github:
    text: 'GitHub'
    url: '#'
    icon: 'https://img.icons8.com/ios-glyphs/24/000000/github.png'
